### PR TITLE
Not a div by zero ebfix but useful nevertheless

### PR DESCRIPTION
**Pull request by mamonu**
deals with #49 ?

### CODE REVIEW

**Comment by RobinL** [comment]
Looks sensible to me!

**Comment by RobinL** [comment]
See example i posted in comments of issue #49

**Comment by RobinL** [comment]
Can confirm my big job (on 100k clusters) works so long as there are no weight=0 edges.  I'll do a PR

**Comment by mamonu** [comment]
So this was not the reason that the div by zero was happening. However this is still useful since there is no reason for doing
modularity calcs on such simple graphs. So still merging it.

**Pull request merged**
